config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @posts = Post.find(params[:post_id])
        @posts.comments.create(comment_params)
        # @post = Post.new(post_params) + @post.save としてもよい
        redirect_to post_path(@posts)
      end

      def destroy
        @posts = Post.find(params[:post_id])
        @comments = @posts.comments.find(params[:id])
        @comments.destroy
        render template: "posts/show"
      end
    
      private
        def comment_params
          params.require(:comment).permit(:body)
        end
    
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order(created_at: 'DESC')
    end

    def show
        @posts = Post.find(params[:id])
    end

    def new
        @posts = Post.new
    end

    def create
        @posts = Post.new(post_params)
        if @posts.save
            flash[:success] = '登録成功しました'
            redirect_to root_path
        else
          flash.now[:danger] = "項目を入力してください"
          render :new
        end
        
    end

    def edit
        @posts = Post.find(params[:id])
    end

    def update
        @posts = Post.find(params[:id])
        if @posts.update(post_params)
            flash[:success] = '成功しました'
            redirect_to root_path
        else
          flash.now[:danger] = "項目を入力してください"
          render :new
        end

    end

    def destroy
        @posts = Post.find(params[:id])
        @posts.destroy
        flash[:success] = '成功しました'
        redirect_to root_path
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Myblog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <h1><%= link_to image_tag( 'MyBLOG.png' ,class: 'logo' ),root_path%></h1>
    <%= yield %>
  </div>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_with model: @posts, local: true do |f| %>

<div class="form-group">
<label for="">タイトル:</label>
<%= f.text_field :title, placeholder: 'enter title', class: 'form-control' %>
</div>

<div class="form-group">
<label for="">内容:</label>
<%= f.text_area :body, placeholder: 'enter body text', class: 'form-control' %>
</div>
<%= f.submit  class: 'btn btn-primary' %>

<% end %>

app/views/posts/edit.html.erb
<h2>編集画面</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>My posts</h3>

<ul class="list-group">
<% @posts.each do |post| %>
    <li class="list-group-item text-muted"><%= link_to post.title, post_path(post.id) %>
    <%= link_to '編集', edit_post_path(post.id), class: "btn btn-primary" %>
    <%= link_to '削除', post_path(post.id),method: :delete,  class: "btn btn-danger",data: {confirm: "本当に削除しますか？"} %>
    </li>
    <% end %>
</ul>
<%= link_to '新規作成',new_post_path, class: "header-menu btn btn-primary" %>

app/views/posts/new.html.erb
<h3>新規作成</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<table class="table">
<h3><%= @posts.title %>詳細画面</h3>
<thead>
<th>id</th>
<th>タイトル</th>
<th>詳細</th>
<th>登録日時</th>
</thead>
<tr>
<td><%= @posts.id %></td>
<td><%= @posts.title %></td>
<td><%= @posts.body %></td>
<td><%= @posts.created_at %></td>
<td><%= link_to '編集', edit_post_path ,class: 'btn btn-primary' %></td>
<td><%= link_to '削除', post_path(@posts.id),method: :delete,  class: "btn btn-danger",data: {confirm: "本当に削除しますか？"} %></td>
</tr>
</table>

<hr>
<h3>Comments</h3>
<% if @posts.comments  %>
<% @posts.comments.each do |comment| %>
<li>
<%= comment.body %>
<%= link_to '[×]', post_comment_path(@posts.id,comment), method: :delete,data: {confirm: "本当に削除しますか？"} %>
</li>
<% end  %>
<% else %>
<h2>NoComment</h2>
<% end %>

<%= form_for ([@posts,@posts.comments.build])do |f| %>

<div class="form-group">
<label for="">コメント:</label>
<%= f.text_field :body, placeholder: 'コメントを入力してください', class: 'form-control' %>
</div>

<%= f.submit  class: 'btn btn-primary' %>

<% end %>